import pytest
from datetime import datetime, timezone

from trading.risk.models import AccountState, Signal, Side
from trading.daemon.heartbeat import TradingHeartbeatDaemon, HeartbeatCycleResult


def test_heartbeat_single_tick_cycle():
    daemon = TradingHeartbeatDaemon(symbols=["BTC/USDT", "ETH/USDT"])
    account = AccountState(equity=10000.0, peak_equity=10000.0)

    # Feed some price history
    daemon.feed_market_data("BTC/USDT", [100.0 + i * 0.1 for i in range(50)])

    def dummy_signal_gen(symbol: str, strat: str, price: float) -> Signal:
        return Signal(
            asset=symbol,
            asset_class="crypto",
            side=Side.LONG,
            entry_price=price,
            confidence=0.85,
            timestamp=datetime.now(timezone.utc),
            rationale=f"Generated by {strat}",
            suggested_stop=price * 0.99,
            suggested_target=price * 1.03,
        )

    res = daemon.tick_cycle(account, signal_generator_fn=dummy_signal_gen)

    assert isinstance(res, HeartbeatCycleResult)
    assert res.cycle_number == 1
    assert res.survival_status.allow_new_entries is True
    assert len(res.approved_orders) > 0
    assert res.elapsed_ms > 0


def test_heartbeat_post_trade_reflection():
    daemon = TradingHeartbeatDaemon()
    # Record closed trade
    daemon.record_closed_trade_reflection(
        trade_id="trade-123",
        symbol="BTC/USDT",
        strategy="trend_momentum",
        regime="trending_bull",
        r_multiple=2.5,
        net_pnl=250.0,
        entry_price=100.0,
        exit_price=102.5,
    )

    # Verify LearningGraph updated
    nodes = daemon.learning_graph.graph.nodes()
    assert ("decision", "trade-123") in nodes
    assert ("result", "trade-123") in nodes

    # Verify Bandit updated
    summary = daemon.bandit_allocator.summary()
    assert summary["trend_momentum"]["avg_reward"] > 0
