from datetime import datetime, timezone

import pytest

from trading.daemon.heartbeat import (HeartbeatCycleResult,
                                      TradingHeartbeatDaemon)
from trading.risk.models import AccountState, Side, Signal


def test_heartbeat_single_tick_cycle(account_state):
    daemon = TradingHeartbeatDaemon(symbols=["BTC/USDT", "ETH/USDT"])
    account = account_state()

    # Feed some price history
    daemon.feed_market_data("BTC/USDT", [100.0 + i * 0.1 for i in range(50)])

    def dummy_signal_gen(symbol: str, strat: str, price: float) -> Signal:
        return Signal(
            asset=symbol,
            asset_class="crypto",
            side=Side.LONG,
            entry_price=price,
            confidence=0.85,
            timestamp=datetime.now(timezone.utc),
            rationale=f"Generated by {strat}",
            suggested_stop=price * 0.99,
            suggested_target=price * 1.03,
        )

    res = daemon.tick_cycle(account, signal_generator_fn=dummy_signal_gen)

    assert isinstance(res, HeartbeatCycleResult)
    assert res.cycle_number == 1
    assert res.survival_status.allow_new_entries is True
    assert len(res.approved_orders) > 0
    assert res.elapsed_ms > 0


def test_heartbeat_post_trade_reflection():
    daemon = TradingHeartbeatDaemon()
    # Record closed trade
    daemon.record_closed_trade_reflection(
        trade_id="trade-123",
        symbol="BTC/USDT",
        strategy="trend_momentum",
        regime="trending_bull",
        r_multiple=2.5,
        net_pnl=250.0,
        entry_price=100.0,
        exit_price=102.5,
    )

    # Verify LearningGraph updated
    nodes = daemon.learning_graph.graph.nodes()
    assert ("decision", "trade-123") in nodes
    assert ("result", "trade-123") in nodes

    # Verify Bandit updated
    summary = daemon.bandit_allocator.summary()
    assert summary["trend_momentum"]["avg_reward"] > 0


# ---------------------------------------------------------------------------
# WAVE4 EX1b additions: data-sufficiency guard + survival entry gating
# ---------------------------------------------------------------------------


def _signal_gen(confidence: float = 0.95):
    def gen(symbol: str, strat: str, price: float) -> Signal:
        return Signal(
            asset=symbol,
            asset_class="crypto",
            side=Side.LONG,
            entry_price=price,
            confidence=confidence,
            timestamp=datetime.now(timezone.utc),
            rationale=f"Generated by {strat}",
            suggested_stop=price * 0.99,
            suggested_target=price * 1.03,
        )

    return gen


def test_wave4_short_buffer_skips_evaluation_no_fabricated_history(
    caplog, account_state
):
    """Short candle buffer => models are NOT fit and NO orders are produced.

    The old behavior fabricated a synthetic 40-point price seed; it must stay dead.
    """
    daemon = TradingHeartbeatDaemon(symbols=["BTC/USDT"], min_candle_buffer=30)
    account = account_state()
    daemon.feed_market_data("BTC/USDT", [100.0, 101.0, 102.0])  # far below warmup

    calls = {"garch": 0}
    orig_fit = daemon.garch_model.fit_forecast

    def spy_fit(prices, *args, **kwargs):
        calls["garch"] += 1
        return orig_fit(prices)

    daemon.garch_model.fit_forecast = spy_fit

    with caplog.at_level("WARNING", logger="trading.daemon.heartbeat"):
        res = daemon.tick_cycle(account, signal_generator_fn=_signal_gen())

    assert calls["garch"] == 0  # evaluation skipped entirely
    assert res.garch_forecast is None  # no fabricated model output
    assert res.hmm_regime is None
    assert res.evt_tail_risk is None
    assert res.approved_orders == []
    assert res.proposed_signals == 0
    assert any(
        "DATA_INSUFFICIENT symbol=BTC/USDT" in r.getMessage() for r in caplog.records
    )


def test_wave4_data_insufficient_warned_once_per_symbol(caplog, account_state):
    daemon = TradingHeartbeatDaemon(symbols=["BTC/USDT"], min_candle_buffer=30)
    account = account_state()
    daemon.feed_market_data("BTC/USDT", [100.0])

    with caplog.at_level("WARNING", logger="trading.daemon.heartbeat"):
        daemon.tick_cycle(account)
        daemon.tick_cycle(account)

    warns = [r for r in caplog.records if "DATA_INSUFFICIENT symbol=" in r.getMessage()]
    assert len(warns) == 1  # once per symbol, not once per cycle


def test_wave4_entry_blocked_in_survival_tier(caplog):
    """Even a high-confidence signal generates zero entries while in SURVIVAL."""
    daemon = TradingHeartbeatDaemon(symbols=["BTC/USDT"], min_candle_buffer=10)
    account = AccountState(
        equity=9000.0,
        peak_equity=10000.0,
        daily_pnl_pct=-0.03,  # breaches daily loss limit -> SURVIVAL
    )
    daemon.feed_market_data("BTC/USDT", [100.0 + i for i in range(20)])  # enough data

    with caplog.at_level("WARNING", logger="trading.daemon.heartbeat"):
        res = daemon.tick_cycle(
            account, signal_generator_fn=_signal_gen(confidence=0.99)
        )

    assert res.survival_status.tier.value == "survival"
    assert res.survival_status.allow_new_entries is False
    assert res.approved_orders == []
    assert any("ENTRY_BLOCKED tier=survival" in r.getMessage() for r in caplog.records)


def test_wave4_async_loop_blocks_and_logs_transitions(caplog):
    """run_async_loop strips any entry orders while defended and logs transitions."""
    import asyncio

    async def run():
        daemon = TradingHeartbeatDaemon(
            symbols=["BTC/USDT"], min_candle_buffer=5, interval_seconds=0.0
        )
        # Start healthy with data so cycle 1 runs the full path.
        daemon.feed_market_data("BTC/USDT", [100.0 + i for i in range(15)])
        states = [
            AccountState(equity=10000.0, peak_equity=10000.0),  # NORMAL
            AccountState(
                equity=9000.0, peak_equity=10000.0, daily_pnl_pct=-0.03
            ),  # -> SURVIVAL
        ]
        holder = {"i": 0}

        def provider():
            state = states[min(holder["i"], len(states) - 1)]
            holder["i"] += 1
            return state

        with caplog.at_level("INFO", logger="trading.daemon.heartbeat"):
            await asyncio.wait_for(
                daemon.run_async_loop(
                    provider, signal_generator_fn=_signal_gen(), max_cycles=2
                ),
                timeout=5.0,
            )

    asyncio.run(run())
    msgs = [r.getMessage() for r in caplog.records]
    assert any("normal -> survival" in m for m in msgs)  # transition telemetry
    assert any(m.startswith("ENTRY_BLOCKED tier=") for m in msgs)
